apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnetworks.aws.platformref.upbound.io
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.platformref.upbound.io/v1alpha1
    kind: XNetwork
  patchSets:
  - name: region
    patches:
    - fromFieldPath: spec.region
      toFieldPath: spec.forProvider.region
  - name: availabilityZone-a
    patches:
    - fromFieldPath: spec.region
      toFieldPath: spec.forProvider.availabilityZone
      transforms:
      - type: string
        string:
          fmt: "%sa"
  - name: availabilityZone-b
    patches:
    - fromFieldPath: spec.region
      toFieldPath: spec.forProvider.availabilityZone
      transforms:
      - type: string
        string:
          fmt: "%sb"
  - name: subnetIdSelectorMatchLabelsZone-a
    patches:
    - fromFieldPath: spec.region
      toFieldPath: spec.forProvider.subnetIdSelector.matchLabels.zone
      transforms:
      - type: string
        string:
          fmt: "%sa"
  - name: subnetIdSelectorMatchLabelsZone-b
    patches:
    - fromFieldPath: spec.region
      toFieldPath: spec.forProvider.subnetIdSelector.matchLabels.zone
      transforms:
      - type: string
        string:
          fmt: "%sa"
  - name: metadataLabelsZone-a
    patches:
    - fromFieldPath: spec.region
      toFieldPath: metadata.labels.zone
      transforms:
      - type: string
        string:
          fmt: "%sa"
  - name: metadataLabelsZone-b
    patches:
    - fromFieldPath: spec.region
      toFieldPath: metadata.labels.zone
      transforms:
      - type: string
        string:
          fmt: "%sb"
  - name: deletionPolicy
    patches:
    - fromFieldPath: spec.deletionPolicy
      toFieldPath: spec.deletionPolicy
  - name: network-id
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.labels[networks.aws.platformref.upbound.io/network-id]
  resources:
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            cidrBlock: 192.168.0.0/16
            enableDnsSupport: true
            enableDnsHostnames: true
            tags:
              Owner: Platform Team
              Name: platformref-vpc
      name: platformref-vcp
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: InternetGateway
        spec:
          forProvider:
            vpcIdSelector:
              matchControllerRef: true
      name: gateway
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: us-region-zone-a
            access: public
        spec:
          forProvider:
            mapPublicIpOnLaunch: true
            cidrBlock: 192.168.0.0/18
            vpcIdSelector:
              matchControllerRef: true
            tags:
              kubernetes.io/role/elb: "1"
      name: subnet-public-region-zone-a
      patches:
        - type: PatchSet
          patchSetName: metadataLabelsZone-a
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: availabilityZone-a
        - type: PatchSet
          patchSetName: network-id
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.subnetIds[0]
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            access: public
        spec:
          forProvider:
            mapPublicIpOnLaunch: true
            cidrBlock: 192.168.64.0/18
            vpcIdSelector:
              matchControllerRef: true
            tags:
              kubernetes.io/role/elb: "1"
      name: subnet-public-region-zone-b
      patches:
        - type: PatchSet
          patchSetName: metadataLabelsZone-b
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: availabilityZone-b
        - type: PatchSet
          patchSetName: network-id
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.subnetIds[1]
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            access: private
        spec:
          forProvider:
            cidrBlock: 192.168.128.0/18
            vpcIdSelector:
              matchControllerRef: true
            tags:
              kubernetes.io/role/internal-elb: "1"
      name: subnet-private-region-zone-a
      patches:
        - type: PatchSet
          patchSetName: metadataLabelsZone-a
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: availabilityZone-a
        - type: PatchSet
          patchSetName: network-id
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.subnetIds[2]
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            access: private
        spec:
          forProvider:
            cidrBlock: 192.168.192.0/18
            vpcIdSelector:
              matchControllerRef: true
            tags:
              kubernetes.io/role/internal-elb: "1"
      name: subnet-private-region-zone-b
      patches:
        - type: PatchSet
          patchSetName: metadataLabelsZone-b
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: availabilityZone-b
        - type: PatchSet
          patchSetName: network-id
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.subnetIds[3]
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            vpcIdSelector:
              matchControllerRef: true
      name: routeTable
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Route
        spec:
          forProvider:
            destinationCidrBlock: 0.0.0.0/0
            gatewayIdSelector:
              matchControllerRef: true
            routeTableIdSelector:
              matchControllerRef: true
      name: route
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: MainRouteTableAssociation
        spec:
          forProvider:
            routeTableIdSelector:
              matchControllerRef: true
            vpcIdSelector:
              matchControllerRef: true
      name: mainRouteTableAssociation
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                access: public
      name: RouteTableAssociation-public-a
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: subnetIdSelectorMatchLabelsZone-a
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                access: public
      name: RouteTableAssociation-public-b
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: subnetIdSelectorMatchLabelsZone-b
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                access: private
      name: RouteTableAssociation-private-a
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: subnetIdSelectorMatchLabelsZone-a
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                access: private
      name: RouteTableAssociation-private-b
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: subnetIdSelectorMatchLabelsZone-b
        - type: PatchSet
          patchSetName: network-id
    - name: securityGroup
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            vpcIdSelector:
              matchControllerRef: true
            name: platform-ref-aws-cluster
            description: Allow access to databases
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: network-id
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.securityGroupIds[0]
    - name: securityGroupRulePostgres
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        spec:
          forProvider:
            type: ingress
            fromPort: 5432
            toPort: 5432
            protocol: tcp
            cidrBlocks:
              - 0.0.0.0/0
            securityGroupIdSelector:
              matchControllerRef: true
            description: Everywhere
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: network-id
    - name: securityGroupRuleMysql
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        spec:
          forProvider:
            type: ingress
            fromPort: 3306
            toPort: 3306
            protocol: tcp
            cidrBlocks:
              - 0.0.0.0/0
            securityGroupIdSelector:
              matchControllerRef: true
            description: Everywhere
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: network-id
